### ISSUE TITLE
fix duplicate and ambiguous variable names

### ISSUE THREAD

**Issue by JessicaS11** [icesat2py/icepyx#104]
some attributes (e.g. `source` and `_source`) have different functionalities. These should be made consistent. Relatedly, `files` is an ambiguous variable name.

**Comment by JessicaS11** [comment]
`dataset` should become `dataset_id` in line with NSIDC terminology

**Comment by weiji14** [comment]
Hi @JessicaS11, are you currently working on this? Also, maybe `dataset` (e.g. ATL06) should be `product` as you mentioned at https://github.com/icesat2py/icepyx/pull/144#discussion_r489482421

**Comment by JessicaS11** [comment]
To update this issue: I've made the changes relating to `source` and `_source`, as well as improved the `files` variable name (I'll note that for the most part, these primarily referred to portions of code that are not-yet-implemented or are used internally to track information, but are not visible to the user).

After some conversation with @nicholas-kotlinski at NSIDC, I've put out a request to the ICESat-2 Science Team for more feedback/guidance on the use of `dataset` versus `product` (versus `dataset_id`), since both terms are considered "correct" but we'd like to go with the community/user preference. A change from `dataset` to `product` would be backwards incompatible, but for existing code a simple find-replace all should take care of the migration. I'll update here or with a PR once we've landed on the best path forward, but please feel free to share your thoughts and opinions here too (or point out any other such ambiguous/duplicate terminology you've found).
