### ISSUE TITLE
structuring of docs (documentation) directory

### ISSUE THREAD

**Issue by JessicaS11** [icesat2py/icepyx#11]
@norlandrhagen and I are working on getting the documentation ready to put on readthedocs. We've come up with a few different ways to structure our documentation based on a number of other repos (including Pandas and altair). I'd like to propose the following directory structure and encourage thoughts and comments. A few of our conversation points that got us here are included as well.
|---doc
|    |---examples (these are at a high level within docs to make it as easy as possible for new users to find them)
|    |    |---NSIDC.ipynb
|    |---source
|    |    |---_icepyx
|    |    |    |--- *.rst
|    |    |--- _static
|    |    |--- getting_started (formerly "usage")
|    |    |    |--- install.rst
|    |    |--- user_guide
|    |    |    |--- is2class.rst
|    |    |--- conf.py
|    |    |--- icepyx.rst
|    |    |--- index.rst
|    |    |--- development
|    |    |    |--- cont_contact.rst (draft file in norlandrhagen/icepyx docs branch)
|    |--- makefile
|    |--- make.bat

**Comment by norlandrhagen** [comment]
Here is a tree-struc of your proposed directory and a trunacted tree-struc of Altair's doc folder:  

icepyx proposed doc struct:
**.
└── doc
    ├── examples
    │   └── NSIDC.ipynb
    ├── make.bat
    ├── makefile
    └── source
        ├── conf.py
        ├── development
        │   └── cont_contact.rst
        ├── getting_started
        │   └── install.rst
        ├── icepyx
        │   ├── 1.rst
        │   ├── 2.rst
        │   └── n.rst
        ├── icepyx.rst
        ├── index.rst
        ├── _static
        └── user_guide
            └── is2class.rst**
altair truncated doc struct:
**.
├── _build
│   ├── doctrees
│   │   ├── case_studies
│   │   │   └── exploring-weather.doctree
│   │   ├── environment.pickle
│   │   ├── gallery [126 entries exceeds filelimit, not opening dir]
│   │   ├── getting_started
│   │   │   ├── installation.doctree
│   │   │   ├── overview.doctree
│   │   │   └── starting.doctree
│   │   ├── index.doctree
│   │   └── user_guide [22 entries exceeds filelimit, not opening dir]
│   └── html
│       ├── case_studies
│       │   └── exploring-weather.html
│       ├── gallery [126 entries exceeds filelimit, not opening dir]
│       ├── genindex.html
│       ├── getting_started
│       │   ├── installation.html
│       │   ├── overview.html
│       │   └── starting.html
│       ├── index.html
│       ├── objects.inv
│       ├── search.html
│       ├── searchindex.js
│       ├── _sources
│       │   ├── case_studies
│       │   │   └── exploring-weather.rst.txt
│       │   ├── gallery [126 entries exceeds filelimit, not opening dir]
│       │   ├── getting_started
│       │   │   ├── installation.rst.txt
│       │   │   ├── overview.rst.txt
│       │   │   └── starting.rst.txt
│       │   ├── index.rst.txt
│       │   └── user_guide [22 entries exceeds filelimit, not opening dir]
│       ├── _static [275 entries exceeds filelimit, not opening dir]
│       └── user_guide [22 entries exceeds filelimit, not opening dir]
├── case_studies
│   └── exploring-weather.rst
├── conf.py
├── data.json
├── gallery [126 entries exceeds filelimit, not opening dir]
├── getting_started
│   ├── installation.rst
│   ├── overview.rst
│   └── starting.rst
├── _images [251 entries exceeds filelimit, not opening dir]
├── index.rst
├── make.bat
├── Makefile
├── requirements.txt
├── _static
│   ├── altair-gallery.css
│   ├── altair-logo-light.png
│   ├── altair-plot.css
│   ├── chart.html
│   ├── custom.css
│   ├── favicon.ico
│   ├── gray-square.png
│   └── theme_overrides.css
├── sync_website.sh
├── _templates
│   └── class.rst
└── user_guide [22 entries exceeds file limit, not opening dir]**

Do you think we should move the index.py, conf.py and makefile to the top level of 'doc/' ?
**.
├── conf.py
├── examples
│   └── NSIDC.ipynb
├── index.rst
├── make.bat
├── makefile
└── source
    ├── development
    │   └── cont_contact.rst
    ├── getting_started
    │   └── install.rst
    ├── icepyx
    │   ├── 1.rst
    │   ├── 2.rst
    │   └── n.rst
    ├── icepyx.rst
    ├── _static
    └── user_guide
        └── is2class.rst**

**Comment by JessicaS11** [comment]
I think we can go either way with the location of index.py, conf.py, and makefile. I'm just as happy to put them in 'doc/' as in 'doc/source/'. Do you have a reason to suggest one over the other?

I think your last proposed doc tree looks great though, with the exception of putting the is2class.rst into the user_guide directory. I will go ahead and start working on the structural changes (on the docs-testing branch). Then you'll be able to add the files you created to improve the docs!

**Comment by norlandrhagen** [comment]
Sounds great! 
I don't have any strong feelings on putting them in doc/ vs doc/source/. The only reason I was thinking in doc/ was to replicate the structure of a few known packages.

**Comment by JessicaS11** [comment]
I restructured the directory and got sphinx working to build docs locally. index.rst and conf.py are in the doc/source/, while makefile is in doc/ to match where sphinx automatically looks for them. Please go ahead and make the awesome additions you worked up!
