### ISSUE TITLE
front facing docs page

### ISSUE THREAD

**Issue by JessicaS11** [icesat2py/icepyx#110]
Turn the front-facing documentation page into a one-stop-shop of information about icepyx (both on GitHub and ReadTheDocs). @fspaolo suggested [Jekyll's page](https://jekyllrb.com/) as an example - everything is captured simply and easily without scrolling. We'd like to implement something analogous for icepyx - all the resources easily accessible in the first place people see!

**Comment by fspaolo** [comment]
An alternative to Jekyll is [Hugo](https://gohugo.io/). Both are well maintained and have a large community. All we need to do is select a theme from their galleries and add it to the `icepyx` repo as [GitHub Pages](https://pages.github.com/).

Jekyll themes: https://jamstackthemes.dev/ssg/jekyll/

Hugo themes: https://themes.gohugo.io/

(you can loose yourself choosing... I warn you)

**Comment by weiji14** [comment]
A few projects in the PyData ecosystem have been moving towards using the [PyData Sphinx Theme](https://pydata-sphinx-theme.readthedocs.io/en/v0.5.2). E.g. [geopandas](https://geopandas.org/index.html) (https://github.com/geopandas/geopandas/pull/1564) and [xarray](https://xarray.pydata.org/en/latest/) (https://github.com/pydata/xarray/pull/4835). The 'front page' seems fairly customizable, and it'll probably be easier to port things over from the current [Read the Docs Sphinx Theme](https://github.com/readthedocs/sphinx_rtd_theme) icepyx is using.

![image](https://user-images.githubusercontent.com/23487320/114115417-e4275a00-9936-11eb-8703-e5607faffffd.png)

If this looks like a good plan, I can open a Pull Request for this and get a demo up and running :smile:
