### ISSUE TITLE
Integrating with Valkyrie - ICESat + Operation IceBridge + ICESat-2

### ISSUE THREAD

**Issue by weiji14** [icesat2py/icepyx#134]
A single source of ice elevation data from 1993 to present?

![Valkyrie coverage from 1993-2019-](https://github.com/nsidc/NSIDC-Data-Tutorials/raw/valkyrie/notebooks/Valkyrie/img/valkyrie-coverage.jpg)

Valkyrie was mentioned at one of the IcePyx team meetings last month, but I just stumbled on the work that @andypbarrett and others have been doing at https://github.com/nsidc/NSIDC-Data-Tutorials/tree/valkyrie.

For those who might not be so familiar with Valkyrie (I'm quite new to it too), here's some introductory links:
- Introduce Valkyries before missions - https://github.com/nsidc/NSIDC-Data-Tutorials/issues/4
- https://nsidc.org/sites/nsidc.org/files/files/UWG%20Harmonized%20Products%20Final.pptx
- https://github.com/nsidc/NSIDC-Data-Tutorials/blob/valkyrie/notebooks/Valkyrie/1_intro_valkyrie.ipynb

Question: Is there anyone in `icepyx` interested in this project? What are some common themes we can work on to benefit the cryosphere community?

**Comment by andypbarrett** [comment]
Glad you found this.

The work for Valkyrie was done by developers at NSIDC; Kevin Beam and Luis
Lopez.

Andy

**Comment by JessicaS11** [comment]
@weiji14 Thanks for posting these resources. I'm going to close this issue and ask that since this is more of an informational/discussion post we move the conversation to our corner of [Pangeo Discourse](https://discourse.pangeo.io/c/science/icesat-2/16) as a new topic.
