### ISSUE TITLE
order_vars subsetting command error

### ISSUE THREAD

**Issue by JohnnyRyan1** [icesat2py/icepyx#145]
I have had trouble subsetting ICESat-2 data (ATL07) over the last few days. The code below worked a few weeks ago: 

```
# Import
import icepyx as ipx

# Earthdata Login credentials
earthdata_uid = 'xxx'
email = 'xxx@xxx.edu'

# Define product, area and time of interest
short_name = 'ATL07'
spatial_extent = [-81, 68, -45, 85]
date_range = ['2019-04-09','2019-04-13']

# Produce data object
region_a = ipx.Query(short_name, spatial_extent, date_range)

# Search for available granules and provide basic summary info about them
region_a.avail_granules()

# Provide EarthData login details
region_a.earthdata_login(earthdata_uid, email)

# Subset variables
region_a.order_vars.append(var_list=['height_segment_height','height_segment_ssh_flag',
                                     'height_segment_quality','height_segment_surface_error_est',
                                     'height_segment_length_seg', 'cycle_number',
                                     'rgt','seg_dist_x', 'latitude','longitude', 'delta_time'])
region_a.subsetparams(Coverage=region_a.order_vars.wanted)

# Place the order
region_a.order_granules()

# Downlod granules
path = '/path/to/folder/'
region_a.download_granules(path)
```

When I try the `region_a.order_vars` command I get the following error:

```
Traceback (most recent call last):

  File "/home/johnny/Documents/Uummannaq_ICESat-2/Scripts/1_ATL07_Download.py", line 34, in <module>
    region_a.order_vars.append(var_list=['height_segment_height','height_segment_ssh_flag',

  File "/home/johnny/anaconda3/envs/icesat2/lib/python3.8/site-packages/icepyx/core/variables.py", line 406, in append
    vgrp, allpaths = self.avail(options=True, internal=True)

  File "/home/johnny/anaconda3/envs/icesat2/lib/python3.8/site-packages/icepyx/core/variables.py", line 94, in avail
    self._avail = is2ref._get_custom_options(

  File "/home/johnny/anaconda3/envs/icesat2/lib/python3.8/site-packages/icepyx/core/is2ref.py", line 86, in _get_custom_options
    normalproj_vals.append(normalproj[0]["normalProj"])

KeyError: 'normalProj'
```

**Comment by asteiker** [comment]
It looks like something may have changed with the service metadata we leverage at NSIDC to surface service options so this `normalProj` value included in that service xml is no longer there. I'll update the issue once I have more information.

**Comment by asteiker** [comment]
I have a fix (`fix-normalproj` branch) in my fork but I did this based off of master since I wasn't sure if this should be merged as a hot fix prior to merging into development. Otherwise I can create a new branch and make updates in is2ref.py as opposed to is2class.py. @JessicaS11 or others involved in active development, if you have any guidance on this, please let me know. Thanks!

**Comment by JessicaS11** [comment]
Thanks for writing a fix, @asteiker! We don't yet have an "official" hotfix workflow, but if you submit a PR to development then we can can do a minor update to master to get the other items sitting on development through. Either way, I'd check that your fork is up-to-date, because the current master shouldn't have anything except a deprecation warning in `is2class.py`.

**Comment by icetianli** [comment]
Just caught the same issue here when trying to access the variable list with `show_custom_options` and `order_vars`: `     84     normalproj = [Projections.attrib for Projections in root.iter("Projections")]
     85     normalproj_vals = []
---> 86     normalproj_vals.append(normalproj[0]["normalProj"])
     87     format_proj = normalproj_vals[0].split(",")
     88     format_proj.remove("")

KeyError: 'normalProj'`

Looks like the `"normalProj"` no longer exists in 'normalproj' anymore...
