### ISSUE TITLE
cannot import name icesat2data from icepyx

### ISSUE THREAD

**Issue by PAUL201709** [icesat2py/icepyx#160]
Hello,

I am trying to install icepyx on my mac, and I tried both using 'pip install icepyx' and 'git clone https://github.com/icesat2py/icepyx.git'

But for either way, it seems the icepyx was installed but icesat2data cannot be found.

I noticed a previous issue, and I cd into the icepyx folder with setup.py and use pip install -e .
However, after this, it still cannot find icesat2data....

>>> import icepyx
>>> from icepyx import icesat2data  
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'icesat2data' from 'icepyx' (/Users/hippobaby/Documents/icepyx/icepyx/__init__.py)

Any help I would greatly appreciate!!

Thanks,
Paul

**Comment by JessicaS11** [comment]
Hello @PAUL201709. Thanks for reaching out. Both of your install methods look correct.

The `icesat2data` class object was [deprecated as of v0.3.1](https://icepyx.readthedocs.io/en/latest/user_guide/documentation/icepyx.html). We transitioned instead to `Query`, as part of a larger effort to separate data access from data analysis. Try updating your syntax to:
```
import icepyx as ipx
ipx.Query(short_name, spatial_extent, date_range)
```

For the most up-to-date [examples](https://icepyx.readthedocs.io/en/latest/getting_started/example_link.html) and [usage](https://icepyx.readthedocs.io/en/latest/user_guide/documentation/icepyx.html), please watch our [documentation](https://icepyx.readthedocs.io/en/latest/index.html) pages. With the library still so young, there could be additional non-forward-compatible changes that will be documented there. It sounds like it could be useful to leave up the deprecation warning for longer as well. Could you share where you found the code you were using for the import statements? I'd like to make sure we didn't miss updating anything when we made the switch!

**Comment by PAUL201709** [comment]
Hi Jessica,

Thank you so much for your help! 

Previously, I used the material from https://github.com/ICESAT-2HackWeek/ICESat2_hackweek_tutorials 
The third class in this series. 

Paul

**Comment by JessicaS11** [comment]
Of course - I'm glad you were able to get things working!

Thanks for sharing which materials you are using. For future reference, the latest versions of the Hackweek tutorials (some had errors corrected or notes added after the 2020 event) can be found at: https://github.com/ICESAT-2HackWeek/2020_ICESat-2_Hackweek_Tutorials
