### ISSUE TITLE
Add necessary headers/metadata to api requests to facilitate metrics collection at NSIDC

### ISSUE THREAD

**Issue by wallinb** [icesat2py/icepyx#165]
I think adding the 'client-id' header with value 'icepyx' to CMR/EGI requests and downloads would enable NSIDC Ops to identify those requests as from icepyx and subsequently provide usage metrics back to icepyx.

**Comment by JessicaS11** [comment]
Thanks for opening this issue, @wallinb, and being willing to take this on. From some emails I have, it looks like the exact syntax is expected to be: `client_string=icepyx`. I'll defer to your "insider" knowledge if that's no longer the case though.

In having a quick look through the code base, it looks like we can add it as a [required parameter](https://github.com/icesat2py/icepyx/blob/944673723dcf8c5ac498cc9c8ac416583d10e8b1/icepyx/core/APIformatting.py#L244) to the APIformatting module pretty easily. I think the outstanding question is whether it should get attached to both search and order requests. It will also need to be added to the relevant unit test.

**Comment by wallinb** [comment]
Happy to help! I was going off the the CMR documentation for 'client_id':

> 
Client-Id - Indicates a name for the client using the CMR API. Specifying this helps Operations monitor query performance per client. It can also make it easier for them to identify your requests if you contact them for assistance.

But it may be different for the ordering API and I think we would want to have both. I'm checking with our ops to be sure.

**Comment by JessicaS11** [comment]
>  I'm checking with our ops to be sure.

Awesome - thanks! I agree that both sounds like the way to go.

**Comment by wallinb** [comment]
Indeed `client_string=icepyx` as a url parameter for EGI requests is correct (and `Client-Id` header for CMR).  

I'm happy to relay metrics from NSIDC on EGI requests, CMR metrics are a bit harder as they are collected somewhere in NASA but I can look into it.
