### ISSUE TITLE
expand subsetting capabilities

### ISSUE THREAD

**Issue by JessicaS11** [icesat2py/icepyx#17]
Currently, it's possible to use NSIDC's subsetter to do temporal and spatial subsetting. ICESat-2 data has many other available subsetting options. If you're interested in expanding icepyx's subsetting capabilities, please let us know! Current next steps are:
1. making it easier for the user to see what subsetting options are available
2. letting the user know if they try to use a subsetting option that's not available for that dataset
3. sending other subsetting parameters to the subsetter in the correct format and adding relevant tests

**Comment by asteiker** [comment]
@JessicaS11: I am definitely interested in collaborating on this. These  are great next steps as far as improved usability and error handling as far as subsetting/reformatting options.

**Comment by liuzheng-arctic** [comment]
I am also interested. Great guidelines to go forward. I will try to add functions to generate the key values to "Coverage" of variables with the user specified variable names.

**Comment by JessicaS11** [comment]
I'm excited about all the interest in improving subsetting. I've talked with a few people who are eager to work on this, so I wanted to get everyone here on the same page.

Currently, an icesat2data object has a `show_custom_options` method (e.g. `region_a.show_custom_option(session)`) that can be called after you've logged in to Earthdata (because this information is behind the Earthdata login, as far as I understand it). This displays a long but functional list of the different subsetting options available. @liuzheng-arctic, perhaps you could start here with turning this into an easier-to-work-with format (e.g. a dict?) that can either be displayed for the user or passed to the subsetter. @asteiker @tsutterley, we're hoping that we can ultimately make this function so that the user can either just feed a dictionary into the "order" step (if they already know the keywords - this functionality is already implemented but not tested, though Zheng said it worked fine for him) OR they can open a widget that will allow them to interactively select which subsetting options they want from a list, where the list of available subsetting options is generated based on their data search parameters.

I opened a new branch (subsetting) for us to work on this, which you should all have push access to. Please push/pull frequently so that we don't duplicate efforts as we all work on this!
