### ISSUE TITLE
add conda info for v0.3.4 release

### ISSUE THREAD

**Issue by JessicaS11** [icesat2py/icepyx#185]
We just officially made icepyx available via conda (see #170 and #179) and are planning to release v0.3.4 very soon to push through some kinks we had to work out after 0.3.3. Though there will be other things added in v0.3.4, I'd like to make sure that we get two conda-related additions made:

- [x] add some [conda badges](https://anaconda.org/conda-forge/icepyx/badges) to our home GitHub page
- [x] add some conda badges to our home docs page
- [x] update the install instructions to at least mention that we're available via conda. More install instructions are needed but can come later
- [x] update the readme to note the option for a conda install

If anyone is able/willing to take on any of these tasks in the next few days, feel free to check or review a PR linked to this issue, otherwise go ahead and submit one (and link this issue).

**Comment by weiji14** [comment]
Ping @surfix who might be interested in helping out :wink:

**Comment by Surfix** [comment]
Yes. Thanks @weiji14 . I am interested. I am just about to start exploring the use of IceSat-2 data for my PhD project and I will be glad to contribute to the package.

**Comment by kelseybisson** [comment]
We added PyPi and Conda badges to the Github home page and are going to update the home docs page next Monday as a subgroup (lead2phyto).

**Comment by weiji14** [comment]
FYI, `icepyx` v0.3.4 is now published on PyPI at https://pypi.org/project/icepyx/0.3.4/, and at conda at https://anaconda.org/conda-forge/icepyx (after merging https://github.com/conda-forge/icepyx-feedstock/pull/1)!

**Comment by wenjieji86** [comment]
Hello everyone, I just started to use Anaconda (thanks @JessicaS11 for the recommendation) for my icesat-python projects. So I installed icepyx to my icesat environment which I believe is the 0.3.4 version. However, I got an error message when trying to import the package, anyone had the same issue and how to resolve it? Thanks!

![Capture](https://user-images.githubusercontent.com/41796259/115267245-32d2b200-a0f6-11eb-8562-9fbe93900621.PNG)
![Capture2](https://user-images.githubusercontent.com/41796259/115267255-349c7580-a0f6-11eb-94f3-1597d5bbcb50.PNG)

**Comment by JessicaS11** [comment]
@wenjieji86 Thanks for sharing your issue and the solution you found!

We've now merged the PR that adds conda install info to our documentation. Thanks @kelseybisson @rtilling @RomiP @weiji14 for your contributions. @wenjieji86 @Surfix we look forward to hearing from you on other issues/PRs!
