### ISSUE TITLE
Search Granule number and Downloads not matching?

### ISSUE THREAD

**Issue by nmt28** [icesat2py/icepyx#186]
Hey,

When searching for data I often notice that the number of downloaded files does not match the number of granules found. For example, I found 78 ATL08 granules over Florida:

print avail granules =  {'Number of available granules': 73, 'Average size of granules (MB)': 15.707173399732875, 'Total size of all granules (MB)': 1146.6236581805001}

yet this only downloads 40 items. Is there something I'm missing here?

**Comment by JessicaS11** [comment]
Hello @nmt28! Thanks for reaching out.

Could you please provide some more details, including the code you are running and on which version of icepyx, that results in this issue? Matthew Rocklin has some great pointers for creating minimal working examples (MWEs) [here](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports). One possible explanation is also outlined in [this Pangeo Discourse forum post](https://discourse.pangeo.io/t/granules-meeting-search-criteria-contain-no-data/760/3).

**Comment by dshean** [comment]
Is this just an issue of tracks that intersect the user-provided box/polygon during initial query, but then don't get downloaded because there are no valid points in the granule over the box/polygon during subsetting?

**Comment by nmt28** [comment]
Hi @JessicaS11, thanks for the reply. Apologies, that's a pretty vague question I posted. My code is:

short_name = 'ATL08'
# Florida box
spatial_extent = [-81.513, 25.078, -80.885, 25.928]
date_range = ['2018-01-01','2021-03-31']
# Default is latest version
#version='003'
start_time='00:00:00'
end_time='23:59:59'

region_a = ipx.Query(short_name, spatial_extent, date_range, start_time, end_time)

earthdata_uid = 'name'
email = 'email'
region_a.earthdata_login(earthdata_uid, email)

print(region_a.reqparams)

print('\n print avail granules = ', region_a.avail_granules())

path = 'file path'
region_a.download_granules(path)

So, I get 73 files returned but then only downloads 40. It seems that what David is suggesting (and which was in the link you posted) seems the most likely cause -I just wanted to know why there was "data missing". I mostly wanted to check that I wasn't doing anything wrong that meant I was not getting all the data

**Comment by JessicaS11** [comment]
Thanks for the update, @nmt28! It sounds like you're all set, so I'm going to close this issue.
