### ISSUE TITLE
cannot import name 'icesat2data' from 'icepyx'

### ISSUE THREAD

**Issue by Sharanb02** [icesat2py/icepyx#210]
![Screenshot 2021-06-21 143519](https://user-images.githubusercontent.com/82048981/122736707-ef372880-d29d-11eb-89b7-d77fe6a829a7.png)

Unable to import icesat2data. importing as "from icepyx.core import icesat2data" works, but all the function calls from that class show error.

**Comment by weiji14** [comment]
Hi @Sharanb02, could you try using `import icepyx as ipx` instead? The `from icepyx import icesat2data` method is used in older icepyx versions (< v0.3). You may want to make sure that you have the latest icepyx version (v0.4.0) installed using `conda install -c conda-forge icepyx==0.4.0`.

**Comment by Sharanb02** [comment]
> Hi @Sharanb02, could you try using `import icepyx as ipx` instead? The `from icepyx import icesat2data` method is used in older icepyx versions (< v0.3). You may want to make sure that you have the latest icepyx version (v0.4.0) installed using `conda install -c conda-forge icepyx==0.4.0`.

Thank you, @weiji14.  It works now. I noticed just now that they have shifted all the functions under icesat2data class to query.
 So after importing the function as mentioned by the function call should be `ipd.Query(...)`  not `ipd.Icesat2Data(...)`
