### ISSUE TITLE
region_a.visualize_spatial_extent() problem

### ISSUE THREAD

**Issue by xinluo2018** [icesat2py/icepyx#224]
Sometimes the spatial extent can't be visualized with .visualize_spatial_extent() function in the latest version. I never encounter this problem in the previous icepyx version

**Comment by xinluo2018** [comment]
I have updated the icepyx to the latest version by 'conda update icepyx'. I have to put the .visualize_spatial_extent() code at the last line of the notebook cell, then the visualization could be executed successfully.  so this problem seems to be solved. Thanks.

**Comment by JessicaS11** [comment]
Excellent - I'm glad to hear that you were able to get it working.
