### ISSUE TITLE
polygon coordinate inputs in incorrect order

### ISSUE THREAD

**Issue by JessicaS11** [icesat2py/icepyx#24]
The NSIDC-API requires polygon vertices to be entered in a clockwise direction and contain only one pole. Currently, data objects can be created with polygons that don't meet these criteria, depending on how the polygon is input by the user. We need to add valid polygon checks and reordering capabilities, then add tests to make sure these new functions are performing correctly.

**Comment by ShashankBice** [comment]
Points reordering should be simple to implement with some math like this: https://stackoverflow.com/questions/51074984/sorting-according-to-clockwise-point-coordinates/51075469. I can try tonight and see if it works..

**Comment by ShashankBice** [comment]
I did a quick hack today, 
```from shapely.geometry import Point,Polygon
import numpy as np
def sort_cord_clockwise(reg_a_poly):
    # this assumes that the first and last coordinate tuples are the same..
    poly = Polygon(reg_a_poly)
    cx,cy = [poly.centroid.xy[0][0],poly.centroid.xy[1][0]]
    xy_sort = (sorted(reg_a_poly[:-1], key = lambda x: np.arctan2((x[1]-cy),(x[0]-cx))))
    #this returns counterclockwise 
    xy_sorted = list(reversed(xy_sort[1:]))
    xy_sorted.append(reg_a_poly[-1])
    out_xy = [reg_a_poly[-1]]+xy_sorted
    return list(out_xy)
```
Input: `sort_cord_clockwise([(-64, 66),(-55, 72),(-55, 66),(-64, 72),(-64, 66)])`
Out: `[(-64, 66), (-64, 72), (-55, 72), (-55, 66), (-64, 66)]`
Input: `sort_cord_clockwise([(-64, 66),(-55, 66),(-64, 72),(-55, 72),(-64, 66)])`
Out: `(-64, 66), (-64, 72), (-55, 72), (-55, 66), (-64, 66)]`

@JessicaS11, Can you check with other problematic inputs, specifically for which you got this error. You can also pass those inputs to me and I can check and refine..

**Comment by JessicaS11** [comment]
Turns out shapely polygons have an `orient` method (thanks to @asteiker for sharing that!)
