### ISSUE TITLE
automate python package index updates

### ISSUE THREAD

**Issue by JessicaS11** [icesat2py/icepyx#247]
Currently, the Python Package Index updates are coded in a Jupyter Notebook and must be run manually. It would be great to:
- [ ] Turn this code into a standalone python script
- [ ] create a GitHub action that runs it as a cron job every few months and adds the changes to the traffic branch

**Comment by learn2phoenix** [comment]
I will be happy to take this up. Can someone point me to the concerned Jupyter notebook?

**Comment by JessicaS11** [comment]
Thanks, @learn2phoenix, and welcome to the icepyx community!

The notebook (and files that store the tracking data) are in [https://github.com/icesat2py/icepyx/tree/development/doc/source/tracking/pypistats](https://github.com/icesat2py/icepyx/tree/development/doc/source/tracking/pypistats). In the `tracking` directory a level up you'll also find a directory for the analogous "traffic" behavior.

Please don't hesitate to reach out if you have any other questions or want to "meet" anyone on the team.

**Comment by learn2phoenix** [comment]
Thanks @JessicaS11 I am on this.

**Comment by learn2phoenix** [comment]
@JessicaS11 I have the changes ready in https://github.com/learn2phoenix/icepyx/blob/247-fix/doc/source/tracking/pypistats/get_pypi_stats.py and https://github.com/learn2phoenix/icepyx/blob/247-fix/.github/workflows/get_pypi_stats.yml . Do they look ok? ALso, how can I test this action?

**Comment by JessicaS11** [comment]
Excellent! Thanks @learn2phoenix. Without having done a detailed review, I think the only change I'd suggest is that we change the action to only run once a month (the traffic data is only stored by GitHub for two weeks, so we need to run it more frequently; PyPI stores the data for 3 or 6 months), and at a different time than the traffic action so that there aren't conflicts trying to commit changes to the traffic branch. I'd say whenever you are ready you can go ahead and create a pull request to merge these changes in.

As for testing, unfortunately there's not really a good way to test actions until they're merged into the code base (it's one of their known weaknesses). The best we can do is run the script locally to see if there are any issues, not merge the updated data and plot files, and then manually trigger the action once we've merged it in to the development branch to make sure it works. We would then create a new PR with any additional changes and make sure everything is working in development before we create and package a new release via the main branch. Let me know if I can help with any of these steps!

**Comment by learn2phoenix** [comment]
@JessicaS11 While testing the script on my local I am always hitting `httpx.HTTPStatusError: Client error '429 TOO MANY REQUESTS' for url 'https://pypistats.org/api/packages/icepyx/overall`. Is there a workaround for this?
If testing this is not suggested, I can raise the PR right away

**Comment by JessicaS11** [comment]
@learn2phoenix apparently this is an [open issue](https://github.com/crflynn/pypistats.org/issues/42) on pypistats, which seems to be unresolved. I actually got the error just trying to go to https://pypistats.org/, which suggests to me we're probably not hitting the site over the limits (since I haven't tried to load that page in weeks). Since the objective here is just to transition to an automated workflow, I'd say let's go ahead with the PR. Then we can open a new issue to focus on the fact that pypistats isn't working.

**Comment by learn2phoenix** [comment]
@JessicaS11 Raised https://github.com/icesat2py/icepyx/pull/271

**Comment by JessicaS11** [comment]
@learn2phoenix Excellent! I just was able to go to https://pypistats.org/, so maybe you can try testing the script again so we know if we need to create a new issue for the access problem we were having yesterday?

**Comment by learn2phoenix** [comment]
@JessicaS11 Tried it again and am getting the same error. I guess we should raise this issue

**Comment by JessicaS11** [comment]
@learn2phoenix I'd added to the existing open [pypistats issue](https://github.com/crflynn/pypistats.org/issues/42#event-6006748996) I linked to the other day and there was just a response from the maintainer. It sounds like we should be good to go. : )
