### ISSUE TITLE
AttributeError: module 'icepyx' has no attribute 'Read'

### ISSUE THREAD

**Issue by fxxkccplz** [icesat2py/icepyx#248]
Reading this notebook 'examples/ICESat-2_Data_Read-in_Example.ipynb', but an error that module 'icepyx' has no attribute 'Read' occurred . I have also read the official document, no attribute 'Read' exists, and using 'h5py' to read .h5 file is recommanded.Does it means this notebook need to update?
PS:Some of the docs from official website such as [ICESat-2_DAAC_DataAccess_working](https://icepyx.readthedocs.io/en/latest/dev-notebooks/ICESat-2_DAAC_DataAccess_working.html), the ouptut cells of which are too long , are hard to read.

**Comment by weiji14** [comment]
Hi @fxxkccplz, the 'Read' module is a new feature which has not been released yet, but is available on the icepyx development branch. We will be making a release soon (see #246), but in the meantime, you can try doing `pip install git+https://github.com/icesat2py/icepyx.git@development` (following https://stackoverflow.com/questions/20101834/pip-install-from-git-repo-branch/20101940#20101940) to get the feature.

**Comment by fxxkccplz** [comment]
Thank you, I see. Just cloned this repository and installed by pip manually, and it did work.
