### ISSUE TITLE
PRs from forks fail Travis CI with `Earthdata authentication failed`

### ISSUE THREAD

**Issue by JessicaS11** [icesat2py/icepyx#272]
In #271 we ran into the issue of all Travis-CI tests erroring after the setup in `conftest.py` failed because of secret environment variables. Travis-CI does not allow use of encrypted env variables for external (fork-based) PRs because it's a security risk. We need to modify our CI setup ([e.g.](https://docs.travis-ci.com/user/pull-requests/#pull-requests-and-security-restrictions)) so that tests that don't require the env variable can still run for forked PRs.

Example Travis CI failure from a fork PR:

```
FAILED icepyx/tests/test_auth.py::test_get_session - icepyx.core.auth.AuthenticationError: Earthdata authentication failed. Check output for error message

FAILED icepyx/tests/test_auth.py::test_get_s3login_credentials - icepyx.core.auth.AuthenticationError: Earthdata authentication failed. Check output for error message

FAILED icepyx/tests/test_auth.py::test_login_function - icepyx.core.auth.AuthenticationError: Earthdata authentication failed. Check output for error message
```

**Comment by mfisher87** [comment]
I think we can split up our tests into integration tests which require EDL (or other third-party services) and unit tests which don't, and only run unit tests on PRs from forks. Thoughts?

**Comment by mfisher87** [comment]
:scream: I just discovered that branch protections are preventing me from merging PRs from forks (e.g. #557)

Breaking the tests up into two parts would address this, but for now can I be permitted to bypass branch protection?

**Comment by mfisher87** [comment]
I applied a quick fix to split the tests. In the long run, I'd like to organize the tests into two folders (unit, integration), and provide scripts or [tasks](https://learn.scientific-python.org/development/guides/tasks/) to run the tests separately. It will clear which have external dependencies and which don't, but that's not urgent :)
