### ISSUE TITLE
NSIDC not implemented error with readable_granule_name

### ISSUE THREAD

**Issue by JessicaS11** [icesat2py/icepyx#278]
An extension of #274, the ability to order granules by readable_granule_name is not working. Specifically, 

```
request_params= {'short_name': 'ATL06',
 'version': '005',
 'options[readable_granule_name][pattern]': 'true',
 'options[spatial][or]': 'true',
 'readable_granule_name[]': ['ATL06_??????????????_084903??_*',
  'ATL06_??????????????_090203??_*',
  'ATL06_??????????????_084904??_*',
  'ATL06_??????????????_090204??_*',
  'ATL06_??????????????_084905??_*',
  'ATL06_??????????????_090205??_*',
  'ATL06_??????????????_084906??_*',
  'ATL06_??????????????_090206??_*',
  'ATL06_??????????????_084907??_*',
  'ATL06_??????????????_090207??_*'],
 'polygon': '-55.0,68.0,-48.0,68.0,-48.0,71.0,-55.0,71.0,-55.0,68.0',
 'page_size': 2000,
 'page_num': 1,
 'request_mode': 'async',
 'include_meta': 'Y',
 'client_string': 'icepyx'}

session.get("https://n5eil02u.ecs.nsidc.org/egi/request", params=request_params) 
```
returns:
```HTTPError: 501 Server Error: Not Implemented for url: https://n5eil02u.ecs.nsidc.org/egi/request?short_name=ATL06&version=005&options%5Breadable_granule_name%5D%5Bpattern%5D=true&options%5Bspatial%5D%5Bor%5D=true&readable_granule_name%5B%5D=ATL06_%3F%3F%3F%3F%3F%3F%3F%3F%3F%3F%3F%3F%3F%3F_084903%3F%3F_%2A&readable_granule_name%5B%5D=ATL06_%3F%3F%3F%3F%3F%3F%3F%3F%3F%3F%3F%3F%3F%3F_090203%3F%3F_%2A&readable_granule_name%5B%5D=ATL06_%3F%3F%3F%3F%3F%3F%3F%3F%3F%3F%3F%3F%3F%3F_084904%3F%3F_%2A&readable_granule_name%5B%5D=ATL06_%3F%3F%3F%3F%3F%3F%3F%3F%3F%3F%3F%3F%3F%3F_090204%3F%3F_%2A&readable_granule_name%5B%5D=ATL06_%3F%3F%3F%3F%3F%3F%3F%3F%3F%3F%3F%3F%3F%3F_084905%3F%3F_%2A&readable_granule_name%5B%5D=ATL06_%3F%3F%3F%3F%3F%3F%3F%3F%3F%3F%3F%3F%3F%3F_090205%3F%3F_%2A&readable_granule_name%5B%5D=ATL06_%3F%3F%3F%3F%3F%3F%3F%3F%3F%3F%3F%3F%3F%3F_084906%3F%3F_%2A&readable_granule_name%5B%5D=ATL06_%3F%3F%3F%3F%3F%3F%3F%3F%3F%3F%3F%3F%3F%3F_090206%3F%3F_%2A&readable_granule_name%5B%5D=ATL06_%3F%3F%3F%3F%3F%3F%3F%3F%3F%3F%3F%3F%3F%3F_084907%3F%3F_%2A&readable_granule_name%5B%5D=ATL06_%3F%3F%3F%3F%3F%3F%3F%3F%3F%3F%3F%3F%3F%3F_090207%3F%3F_%2A&polygon=-55.0%2C68.0%2C-48.0%2C68.0%2C-48.0%2C71.0%2C-55.0%2C71.0%2C-55.0%2C68.0&page_size=2000&page_num=1&request_mode=async&include_meta=Y&client_string=icepyx&Boundingshape=%7B%22type%22%3A%22FeatureCollection%22%2C%22features%22%3A%5B%7B%22id%22%3A%220%22%2C%22type%22%3A%22Feature%22%2C%22properties%22%3A%7B%7D%2C%22geometry%22%3A%7B%22type%22%3A%22Polygon%22%2C%22coordinates%22%3A%5B%5B%5B-55.0%2C68.0%5D%2C%5B-48.0%2C68.0%5D%2C%5B-48.0%2C71.0%5D%2C%5B-55.0%2C71.0%5D%2C%5B-55.0%2C68.0%5D%5D%5D%7D%2C%22bbox%22%3A%5B-55.0%2C68.0%2C-48.0%2C71.0%5D%7D%5D%2C%22bbox%22%3A%5B-55.0%2C68.0%2C-48.0%2C71.0%5D%7D``` (as originally cited by @nitin-ravinder in #274).

@betolink @andypbarrett @tsutterley Anything jump out immediately as causing the issue? Given these examples worked previously, I'm wondering if there was a CMR change that we need to update for?

**Comment by tsutterley** [comment]
I think that readable granule names still works for CMR queries but they are solely `CMRparams` not `reqparams`.  Since this looks like they're being used as request parameters to the NSIDC API, I'd have to dig back into the code to figure out why.  I thought they only got added for CMR queries.

**Comment by JessicaS11** [comment]
Repeating you to make sure I have it right: readable granule names are valid for CMR queries, but not for the order request itself (which would match with the error message)? Here `reqparams` is actually "required parameters" that MUST be supplied to submit a request (with the specific parameters depending on whether it's a CMR query or order to the NSIDC API). So it sounds like they are getting carried through to the order placing but shouldn't be... I'll see if I can figure out what may have changed on the icepyx end to trigger this, unless we hear from NSIDC that something changed on their end.

**Comment by JessicaS11** [comment]
@nitin-ravinder I wanted to follow up here that NSIDC has opened a ticket to add `readable_granule_name` as an allowable input for data orders. In the meantime, I will update the icepyx data access example to note that you can search for granules by cycle and track, but can currently only order using spatial and temporal parameters (there is no way to specify a set of granules to order programmatically by name). If you have any other suggestions for how we can get around this issue in the meantime, please share here or open a PR with them.

**Comment by nitin-ravinder** [comment]
@JessicaS11, thanks a lot for clarifying the issue! I'm sorry for getting back so late, I was quite busy as I was relocating. At this point, I cannot offer any suggestions as I'm still familiarising myself with icepyx. I will get in touch when I can think of something.

**Comment by JessicaS11** [comment]
See the updated comment in #292. After further digging, it looks like we found an edge case in the subsetter versus CMR API implementations of `readable_granule_name`. The former can only handle one string, while the latter will search for a list of strings. Namely:
```
request_params= {'short_name': 'ATL06',
 'version': '005',
 'options[readable_granule_name][pattern]': 'true',
 'options[spatial][or]': 'true',
 'readable_granule_name[]': ['ATL06_??????????????_084903??_*'],
 'polygon': '-55.0,68.0,-48.0,68.0,-48.0,71.0,-55.0,71.0,-55.0,68.0',
 'page_size': 2000,
 'page_num': 1,
 'request_mode': 'async',
 'include_meta': 'Y',
 'client_string': 'icepyx'}
```

worked, but:
```
request_params= {'short_name': 'ATL06',
 'version': '005',
 'options[readable_granule_name][pattern]': 'true',
 'options[spatial][or]': 'true',
 'readable_granule_name[]': ['ATL06_??????????????_084903??_*',
  'ATL06_??????????????_090203??_*',
  'ATL06_??????????????_084904??_*',
  'ATL06_??????????????_090204??_*',
  'ATL06_??????????????_084905??_*',
  'ATL06_??????????????_090205??_*',
  'ATL06_??????????????_084906??_*',
  'ATL06_??????????????_090206??_*',
  'ATL06_??????????????_084907??_*',
  'ATL06_??????????????_090207??_*'],
 'polygon': '-55.0,68.0,-48.0,68.0,-48.0,71.0,-55.0,71.0,-55.0,68.0',
 'page_size': 2000,
 'page_num': 1,
 'request_mode': 'async',
 'include_meta': 'Y',
 'client_string': 'icepyx'}
```
doesn't when submitting an order.

@nitin-ravinder, could you check that your use case works with the updates? Would you be able/willing to review the PR?

**Comment by nitin-ravinder** [comment]
Hi @JessicaS11, thanks a lot for the update! I'm not sure I know things well enough to be able to review it. I'm not very experienced with git and am still learning it, so I'm not sure what a review entails. I would like to learn and be of some help. Perhaps, I can attend an icepyx meeting and have a discussion there. I'm currently preparing for my first conference at the end of this month, so the one June works well for me. I'm extremely sorry if I'm asking too much while offering very little to this community. I'm fairly new to all of this.

**Comment by JessicaS11** [comment]
Thanks, @nitin-ravinder! I'm working on a "how to do a GitHub code review" guide for the The Turing Way, but until I complete it... as with any review, the goal is to provide feedback. In the case of software/documentation, your role as a reviewer is to look over the additions and (as in this case) test the code to make sure that the issue is actually resolved (and that we haven't created any new ones). GitHub provides some great tools to help make that easier, and we've set up a bunch of testing to help with the process. One of my roles with icepyx is to help welcome new contributors and provide guidance/training on getting involved, so I'd be happy to walk you through the basics at an icepyx meeting or another time, as you're available. Reporting bugs and responding to updates/comments is already a great contribution, so thanks for doing those things!

**Comment by nitin-ravinder** [comment]
Thanks, @JessicaS11! I'm extremely sorry for taking so long to get back on this. Yes, a walk-through would be really helpful to get started. I can join in on the next icepyx meeting (14th June) if that works or I'm available at another time too, if that's better.

**Comment by JessicaS11** [comment]
@nitin-ravinder no worries! The Tuesday 14 June icepyx meeting sounds like a great idea - let's plan to do a PR review walk-through then.

**Comment by nitin-ravinder** [comment]
Great! Thanks, @JessicaS11 :)
