### ISSUE TITLE
AttributeError: partially initialized module 'fiona' has no attribute '_loading' (most likely due to a circular import)

### ISSUE THREAD

**Issue by nmt28** [icesat2py/icepyx#302]
Installation via conda on Mar 31 2022 is successful but returns this error when icepyx is run:

AttributeError: partially initialized module 'fiona' has no attribute '_loading' (most likely due to a circular import)

**Comment by JessicaS11** [comment]
Hello @nmt28! Are you trying to install into an existing conda environment, or creating a new one that includes icepyx? Fiona recently logged this [same error](https://github.com/conda-forge/fiona-feedstock/issues/192#issuecomment-1081503866) and traced it to a gdal release made around the same time as their update. As best I can tell, both libraries have released fixes, and I was unable to reproduce the error when I created a fresh conda environment with icepyx. Please let us know how it goes and if you're still having this issue!

**Comment by nmt28** [comment]
Yes I was installing it into a new env, built upon python=3.9. It seems like the new GDAL builds have been breaking a lot of things recently. I did see one solution that recommended installing Fiona before geopandas. The pip install works fine so I ended up using that one.

I'm running it on Mac OS

**Comment by nmt28** [comment]
Yeah that works for me. I'm increasingly having to pin versions of things - especially anything that uses rasterio which does NOT play nicely with GDAL. I also used mamba - sorry I should have been more specific there. I think giving them a couple of days to sort it out is a good idea for now. As long as the pip version works, it should be fine in the short term.

**Comment by weiji14** [comment]
> Any thoughts on creating a docker image? Or is that another can of worms? That doesn't actually solve my problem specifically as UMD do not allow docker...!

There was some effort into making a docker image at https://github.com/icesat2py/icepyx-examples-image, but that didn't go very far for some reason.

>What dependency requires GDAL within icepyx?

Looking at https://github.com/icesat2py/icepyx/blob/v0.6.2/requirements.txt, I would say fiona is the key one that uses GDAL directly.

But back to your original installation problem, the conda-forge issues should sort themselves out in a few days. It's quite rare that things break like this, and usually people are onto it pretty quickly (since so many geo- packages use GDAL et al). Pinning package versions is definitely something to look into though, you can try reading up on it at https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html#building-identical-conda-environments or try using a lockfile manager like https://github.com/conda-incubator/conda-lock.

**Comment by jorisvandenbossche** [comment]
@nmt28 could you show the output of `conda list` of the broken environment? (so we can check the exact build versions that is being used). As @weiji14 mentioned, this is getting handled in conda-forge, but I expected that the latest build should be working again (unless the issue of a few days ago reappeared).

**Comment by nmt28** [comment]
@jorisvandenbossche 

current conda list:

#
# Name                    Version                   Build  Channel
appdirs                   1.4.4              pyh9f0ad1d_0    conda-forge
asciitree                 0.3.3                      py_2    conda-forge
attrs                     21.4.0             pyhd8ed1ab_0    conda-forge
backoff                   1.11.1             pyhd8ed1ab_0    conda-forge
bleach                    4.1.0              pyhd8ed1ab_0    conda-forge
bokeh                     2.4.2            py39h6e9494a_0    conda-forge
boost-cpp                 1.74.0               hff03dee_4    conda-forge
branca                    0.4.2              pyhd8ed1ab_0    conda-forge
brotli                    1.0.9                h0d85af4_6    conda-forge
brotli-bin                1.0.9                h0d85af4_6    conda-forge
brotlipy                  0.7.0           py39h89e85a6_1003    conda-forge
bzip2                     1.0.8                h0d85af4_4    conda-forge
c-ares                    1.18.1               h0d85af4_0    conda-forge
ca-certificates           2022.3.29            hecd8cb5_0  
cairo                     1.16.0            he43a7df_1008    conda-forge
cartopy                   0.18.0           py39hf1ba7ce_1  
certifi                   2021.10.8        py39h6e9494a_2    conda-forge
cffi                      1.15.0           py39hc55c11b_1  
cfitsio                   3.470                h01dc385_7    conda-forge
cftime                    1.6.0            py39h86b5767_0    conda-forge
charset-normalizer        2.0.12             pyhd8ed1ab_0    conda-forge
click                     8.1.2            py39h6e9494a_0    conda-forge
click-plugins             1.1.1                      py_0    conda-forge
cligj                     0.7.2              pyhd8ed1ab_1    conda-forge
cloudpickle               2.0.0              pyhd8ed1ab_0    conda-forge
colorama                  0.4.4              pyh9f0ad1d_0    conda-forge
colorcet                  3.0.0              pyhd8ed1ab_0    conda-forge
cryptography              36.0.2           py39h1644bb1_0    conda-forge
curl                      7.80.0               hca72f7f_0  
cycler                    0.11.0             pyhd8ed1ab_0    conda-forge
cytoolz                   0.11.2           py39h89e85a6_1    conda-forge
dask                      2022.3.0           pyhd8ed1ab_0    conda-forge
dask-core                 2022.3.0           pyhd8ed1ab_0    conda-forge
datashader                0.13.0             pyh6c4a22f_0    conda-forge
datashape                 0.5.4                      py_1    conda-forge
distributed               2022.3.0           pyhd8ed1ab_0    conda-forge
entrypoints               0.4                pyhd8ed1ab_0    conda-forge
expat                     2.4.4                he49afe7_0    conda-forge
fasteners                 0.17.3             pyhd8ed1ab_0    conda-forge
fiona                     1.8.21           py39haa9df5e_0    conda-forge
folium                    0.12.1.post1       pyhd8ed1ab_1    conda-forge
fontconfig                2.13.96              h10f422b_0    conda-forge
fonttools                 4.31.2           py39h63b48b0_0    conda-forge
freetype                  2.11.0               hd8bbffd_0  
freexl                    1.0.6                h0d85af4_0    conda-forge
fsspec                    2022.2.0           pyhd8ed1ab_0    conda-forge
gdal                      3.4.1            py39h339f5b9_0  
geopandas                 0.10.2             pyhd8ed1ab_1    conda-forge
geopandas-base            0.10.2             pyha770c72_1    conda-forge
geos                      3.8.0                h4a8c4bd_1    conda-forge
geotiff                   1.7.0                hf77b895_0  
geoviews                  1.9.5              pyhd8ed1ab_0    conda-forge
geoviews-core             1.9.5              pyha770c72_0    conda-forge
gettext                   0.21.0               h7535e17_0  
giflib                    5.2.1                hbcb3906_2    conda-forge
h5netcdf                  1.0.0              pyhd8ed1ab_0    conda-forge
h5py                      3.6.0            py39h4a1dd59_0  
hdf4                      4.2.13            hefd3b78_1005    conda-forge
hdf5                      1.10.6          nompi_hc5d9132_1114    conda-forge
heapdict                  1.0.1                      py_0    conda-forge
holoviews                 1.14.8             pyhd8ed1ab_0    conda-forge
hvplot                    0.7.3              pyh6c4a22f_0    conda-forge
icepyx                    0.6.2              pyhd8ed1ab_0    conda-forge
icu                       68.2                 he49afe7_0    conda-forge
idna                      3.3                pyhd8ed1ab_0    conda-forge
importlib-metadata        4.11.3           py39h6e9494a_1    conda-forge
importlib_metadata        4.11.3               hd8ed1ab_1    conda-forge
intake                    0.6.5              pyhd8ed1ab_0    conda-forge
intake-xarray             0.6.0              pyhd8ed1ab_0    conda-forge
jbig                      2.1               h0d85af4_2003    conda-forge
jinja2                    3.1.1              pyhd8ed1ab_0    conda-forge
joblib                    1.1.0              pyhd8ed1ab_0    conda-forge
jpeg                      9e                   h0d85af4_0    conda-forge
json-c                    0.13.1            h575e443_1002    conda-forge
kealib                    1.4.14               h31dd65d_2    conda-forge
kiwisolver                1.3.2            py39hf018cea_1    conda-forge
krb5                      1.19.2               hcfbf3a7_3    conda-forge
lcms2                     2.12                 h577c468_0    conda-forge
lerc                      2.2.1                h046ec9c_0    conda-forge
libblas                   3.9.0           13_osx64_openblas    conda-forge
libbrotlicommon           1.0.9                h0d85af4_6    conda-forge
libbrotlidec              1.0.9                h0d85af4_6    conda-forge
libbrotlienc              1.0.9                h0d85af4_6    conda-forge
libcblas                  3.9.0           13_osx64_openblas    conda-forge
libcurl                   7.80.0               h6dfd666_0  
libcxx                    12.0.0               h2f01273_0  
libdap4                   3.19.1            hae55d67_1000    conda-forge
libdeflate                1.7                  h35c211d_5    conda-forge
libedit                   3.1.20210910         hca72f7f_0  
libev                     4.33                 haf1e3a3_1    conda-forge
libffi                    3.3                  hb1e8313_2  
libgdal                   3.4.1                h874363e_0  
libgfortran               5.0.0           9_3_0_h6c81a4c_23    conda-forge
libgfortran5              9.3.0               h6c81a4c_23    conda-forge
libglib                   2.68.4               hd556434_0    conda-forge
libiconv                  1.16                 haf1e3a3_0    conda-forge
libkml                    1.3.0             h8fd9edb_1014    conda-forge
liblapack                 3.9.0           13_osx64_openblas    conda-forge
libllvm10                 10.0.1               h009f743_3    conda-forge
libnetcdf                 4.8.1                h24cb85c_1  
libnghttp2                1.46.0               ha29bfda_0  
libopenblas               0.3.18          openmp_h3351f45_0    conda-forge
libpng                    1.6.37               h7cec526_2    conda-forge
libpq                     12.9                 h1c9f633_1  
libspatialindex           1.9.3                he49afe7_4    conda-forge
libspatialite             4.3.0a            h9691d84_1033    conda-forge
libssh2                   1.10.0               h52ee1ee_2    conda-forge
libtiff                   4.3.0                h1167814_1    conda-forge
libwebp                   1.2.2                h28dabe5_0    conda-forge
libwebp-base              1.2.2                h0d85af4_1    conda-forge
libxml2                   2.9.12               h93ec3fd_0    conda-forge
libzip                    1.8.0                h8b0c345_1    conda-forge
llvm-openmp               13.0.1               hcb1a161_1    conda-forge
llvmlite                  0.36.0           py39h798a4f4_0    conda-forge
locket                    0.2.1            py39hecd8cb5_2  
lz4-c                     1.9.3                he49afe7_1    conda-forge
mapclassify               2.4.3              pyhd8ed1ab_0    conda-forge
markdown                  3.3.6              pyhd8ed1ab_0    conda-forge
markupsafe                2.1.1            py39h63b48b0_1    conda-forge
matplotlib-base           3.5.1            py39hb07454d_0    conda-forge
msgpack-python            1.0.3            py39hf018cea_0    conda-forge
multipledispatch          0.6.0                      py_0    conda-forge
munch                     2.5.0                      py_0    conda-forge
munkres                   1.1.4              pyh9f0ad1d_0    conda-forge
ncurses                   6.3                  hca72f7f_2  
netcdf4                   1.5.7           nompi_py39h8cf34ae_101    conda-forge
networkx                  2.7.1              pyhd8ed1ab_1    conda-forge
numba                     0.53.1           py39h32e38f5_1    conda-forge
numcodecs                 0.9.1            py39h9fcab8e_2    conda-forge
numpy                     1.22.2           py39h9d9ce41_0    conda-forge
openjpeg                  2.4.0                h6e7aa92_1    conda-forge
openssl                   1.1.1n               h6c3fc93_0    conda-forge
packaging                 21.3               pyhd8ed1ab_0    conda-forge
pandas                    1.4.1            py39h4d6be9b_0    conda-forge
panel                     0.12.7             pyhd8ed1ab_0    conda-forge
param                     1.12.1             pyh6c4a22f_0    conda-forge
partd                     1.2.0              pyhd8ed1ab_0    conda-forge
pcre                      8.45                 he49afe7_0    conda-forge
pillow                    9.0.1            py39hde71d04_0  
pip                       21.2.4           py39hecd8cb5_0  
pixman                    0.40.0               hbcb3906_0    conda-forge
poppler                   0.89.0               hd735947_5    conda-forge
poppler-data              0.4.11               hd8ed1ab_0    conda-forge
proj                      6.2.1                h773a61f_0    conda-forge
psutil                    5.9.0            py39h89e85a6_0    conda-forge
pycparser                 2.21               pyhd8ed1ab_0    conda-forge
pyct                      0.4.6                      py_0    conda-forge
pyct-core                 0.4.6                      py_0    conda-forge
pyopenssl                 22.0.0             pyhd8ed1ab_0    conda-forge
pyparsing                 3.0.7              pyhd8ed1ab_0    conda-forge
pyproj                    2.6.1.post1      py39hdfdfadc_1  
pyshp                     2.2.0              pyhd8ed1ab_0    conda-forge
pysocks                   1.7.1            py39h6e9494a_4    conda-forge
python                    3.9.11               hdfd78df_2  
python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
python_abi                3.9                      2_cp39    conda-forge
pytz                      2022.1             pyhd8ed1ab_0    conda-forge
pyviz_comms               2.2.0              pyhd8ed1ab_0    conda-forge
pyyaml                    6.0              py39h63b48b0_4    conda-forge
readline                  8.1.2                hca72f7f_1  
requests                  2.27.1             pyhd8ed1ab_0    conda-forge
rtree                     0.9.7            py39h7d0d40a_3    conda-forge
scikit-learn              1.0.2            py39hd4eea88_0    conda-forge
scipy                     1.8.0            py39h056f1c0_1    conda-forge
setuptools                58.0.4           py39hecd8cb5_0  
shapely                   1.7.1            py39h9250791_0  
six                       1.16.0             pyh6c4a22f_0    conda-forge
sortedcontainers          2.4.0              pyhd8ed1ab_0    conda-forge
sqlite                    3.38.2               h707629a_0  
tblib                     1.7.0              pyhd8ed1ab_0    conda-forge
threadpoolctl             3.1.0              pyh8a188c0_0    conda-forge
tiledb                    2.4.0                h1015a7f_2    conda-forge
tk                        8.6.11               h7bc2e8c_0  
toolz                     0.11.2             pyhd8ed1ab_0    conda-forge
tornado                   6.1              py39h89e85a6_2    conda-forge
tqdm                      4.63.1             pyhd8ed1ab_0    conda-forge
typing_extensions         4.1.1              pyha770c72_0    conda-forge
tzdata                    2022a                hda174b7_0  
unicodedata2              14.0.0           py39h89e85a6_0    conda-forge
urllib3                   1.26.9             pyhd8ed1ab_0    conda-forge
webencodings              0.5.1                      py_1    conda-forge
wheel                     0.37.1             pyhd3eb1b0_0  
xarray                    2022.3.0           pyhd8ed1ab_0    conda-forge
xerces-c                  3.2.3                h379762d_3    conda-forge
xyzservices               2022.3.0           pyhd8ed1ab_0    conda-forge
xz                        5.2.5                h1de35cc_0  
yaml                      0.2.5                h0d85af4_2    conda-forge
zarr                      2.11.1             pyhd8ed1ab_0    conda-forge
zict                      2.1.0              pyhd8ed1ab_0    conda-forge
zipp                      3.7.0              pyhd8ed1ab_1    conda-forge
zlib                      1.2.11               h4dc903c_4  
zstd                      1.5.0                h582d3a0_0    conda-forge

**Comment by jorisvandenbossche** [comment]
@nmt28 you have older versions for some libraries (GDAL is a recent 3.4.1 (although there is a more recent 3.4.2), but eg proj / pyproj are quite old). Did you pin certain versions of packages? It might be that the specific combination of versions because of that is no longer working ..

**Comment by nmt28** [comment]
no, no pinning on my end just:

mamba create -n name python=3.9
mamba install -c condo-forge icepyx

**Comment by nmt28** [comment]
ok, seems like pyproj=3 may have worked. I'm no longer getting the import error. Pyproj is seems to be the source of many of my errors - it likes 2.6.1 by default for some reason

**Comment by nmt28** [comment]
Do you think we can close this out as a pyproj version error on Mac OS?

**Comment by jorisvandenbossche** [comment]
I am not familiar enough with the situation to say. I know there were some other reported issues for MacOS related to pyproj (https://github.com/conda-forge/fiona-feedstock/issues/194), but that was for older python versions. 
In any case, if forcing pyproj >= 3 in your env works and resolves the issues, that sounds as a good solution.

**Comment by JessicaS11** [comment]
> There was some effort into making a docker image at https://github.com/icesat2py/icepyx-examples-image, but that didn't go very far for some reason.

@weiji14 The person working on it switched jobs.

> Do you think we can close this out as a pyproj version error on Mac OS?

@nmt28 I think so - I was able to import icepyx successfully inside `mamba create -n ipxtest -c conda-forge icepyx`, which we could not last week. If I try to create the env in two steps (installing icepyx inside an existing environment) I still get import errors, but not THIS ISSUE'S AttributeError (instead it's a jinja2 ImportError coming from panel, which in this latter env creation is at 0.12.6 instead of 0.12.7).

**Comment by JessicaS11** [comment]
Thanks for your help and input @jorisvandenbossche!
