### ISSUE TITLE
AttributeError: module 'icepyx' has no attribute 'Read'

### ISSUE THREAD

**Issue by lj512lj512** [icesat2py/icepyx#304]
I cannot use icepyx to read the H5 data I download using icepyx. 

When I run dir(icepyx), I got the following result: 

['Query',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 'core']

**Comment by JessicaS11** [comment]
Hello @lj512lj512 - thanks for reaching out!

According to the [documentation](https://docs.python.org/3/library/functions.html#dir), the output of `dir(icepyx)` that you are getting is expected behavior. `icepyx` itself (if from `import icepyx`) is a module, not an object. To use icepyx to read in data, you'll need to create an `icepyx.Read()` class object. Details on how to do this are provided [in this example](https://icepyx.readthedocs.io/en/latest/example_notebooks/IS2_data_read-in.html). Please do reach out if you continue to run into more issues - we're currently working through a few known bugs.

**Comment by lj512lj512** [comment]
Hi Jessica,

Thank you for your reply. But when I run icepyx.Read(), I got the error:
AttributeError: module 'icepyx' has no attribute 'Read'

I used ‘conda install icepyx’.

Kind regards,
Jun

**Comment by JessicaS11** [comment]
@lj512lj512 It looks like you've responded via email - I did some more digging after my initial message and modified my response:
> From the output of dir(icepyx) that you are showing, it looks like your version of icepyx may be out of date and thus not have the Read module. I notice you are also missing Quest(). What version of icepyx are you using (icepyx.__version__)?

**Comment by lj512lj512** [comment]
Hi Jessica,

When I run ‘conda install icepyx’, I have the version of 4.10.3.

***@***.***

Best,
Jun

**Comment by JessicaS11** [comment]
> When I run ‘conda install icepyx’, I have the version of 4.10.3.

That looks like the conda version number (icepyx versions are all <1).

What's the output of:
```
import icepyx as ipx
ipx.__version__
```

**Comment by lj512lj512** [comment]
I got the following answer:
***@***.***
Best,
Jun

**Comment by lj512lj512** [comment]
Hi Jessica,

I created a new environment and reinstall icepyx by the following code:

conda create --name icepyx-env --channel conda-forge icepyx
conda activate icepyx-env

Now, it works.

Do you think it is conflict with other packages, for example, geopandas. Because I have geopandas in the old environment.

Best,
Jun

**Comment by lj512lj512** [comment]
Hi Jessica,
Thank you very much for your help. I can use icepyx now.
But I have another problem when I read ICESat-2 ALT03 that I downloaded using icepyx. The raw ICESat-2 ALT03 (download from the webset directly ) have longitude, latitude, and height variables named ‘lat_ph’, ‘lon_ph’ and ‘h_ph’, but I can’t find them in the icepyx downloaded .h5 files. Do you have any suggestions of this issue? Thank you very much.
Kind regards,
Jun

**Comment by JessicaS11** [comment]
> I created a new environment and reinstall icepyx by the following code:

Yay! I'm glad you got it working.

> Do you think it is conflict with other packages, for example, geopandas. Because I have geopandas in the old environment.

Unlikely. An icepyx install requires geopandas, so your new environment should have geopandas as well. Without knowing what version you were using before, I can't say what the issue was, but I suspect that you were just running an old version of icepyx.


> The raw ICESat-2 ALT03 (download from the webset directly ) have longitude, latitude, and height variables named ‘lat_ph’, ‘lon_ph’ and ‘h_ph’, but I can’t find them in the icepyx downloaded .h5 files.

I'm not sure what's going on. Could you please share the full code you are using to download data with icepyx? I will see if I can reproduce the issue.

**Comment by lj512lj512** [comment]
Hi Jessica,
Thank you very much. I run the code again, and it works now. Maybe I used the old version to download ALT03 data before. I downloaded the data again, and I can find all the variables that I want to use.
Thank you for helping me.
Kind regards,
Jun

**Comment by lj512lj512** [comment]
Hi Jessica,

Thank you again for your timely help. It is a very useful package for ICESat-2 data accessing and processing.
I still have a simple question when using the ‘icepyx.Quary. earthdata_login’ function. I have tried to pass my password to the function, but it doesn’t work.
***@***.***
Do you have any idea of how I can give the password to the function automatically?
Thank you very much.

Kind regards,
Jun

**Comment by JessicaS11** [comment]
I'm so glad you got things working! Thanks for reaching out and I'm glad we were able to figure things out.

As for logging in - it may not be the issue in your code, but in your message "Query" is misspelled as "Quary". For diagnosing issues, please confirm you have the right username and password by logging in directly to [Earthdata](https://urs.earthdata.nasa.gov/). If that's working but you still cannot log in through icepyx, please let me know what output or error message you're receiving (and what code you're running) so we can diagnose from there. Please don't share your password, though!

You can automate the login process using an environment or a .netrc file. We're still working on the icepyx documentation/setup instructions for these features, but [here](https://icesat-2.hackweek.io/preliminary/earthdata.html#configure-programmatic-access-to-nasa-servers) are some instructions for setting up a .netrc for Earthdata authentication. icepyx will check for the .netrc file (and environment variables) automatically (when you run `ipx.Query.earthdata_login()` and only prompt for a password if it doesn't find either of those options.

**Comment by lj512lj512** [comment]
Thank you soooooo much!!!!!
I used git bash to create a .netrc file, and it works. Now I can download the data without manually input my password. Thank you sooooo much.

Kind regards,
Jun
