### ISSUE TITLE
update docs help/contact to reflect activation of GitHub Discussions

### ISSUE THREAD

**Issue by JessicaS11** [icesat2py/icepyx#324]
we recently activated GitHub Discussions for icepyx. It would be good to keep our notes about Pangeo Discourse posts (since they have many helpful tips/conversation), but we should update our docs to encourage posting directly on GitHub, which will make it easier to link issues and PRs to the conversations.

**Comment by siddhant-tripathy1** [comment]
hey, @JessicaS11 could we add to the docs : 
1. https://discourse.pangeo.io/search?q=icepyx (for the posts they could find )
2.  https://github.com/icesat2py/icepyx/discussions(and for the newcomers to engage more in discussions)
