### ISSUE TITLE
local variable 'capability_url' referenced before assignment

### ISSUE THREAD

**Issue by Siyuanhou** [icesat2py/icepyx#374]
Hello, teacher. 
I want to ask you a question. 

capability_url = "https://data.nsidc.earthdatacloud.nasa.gov/s3credentials"
self._session = Earthdata(uid,email,capability_url).login()

Script query error , when I try to down the data. It is OK a few months ago, not this month. Is the Web page updated？

**Comment by JessicaS11** [comment]
Hello @Siyuanhou - thanks for reaching out. The `capability_url` you cited is for cloud data access (only). Are you on the early access list with NSIDC for beta test access to ICESat-2 data in the cloud? If not, you will not be able to create the proper credentials to access ICESat-2 data in the cloud (and you would likely not be downloading the data in a cloud-access scenario).

If you continue to have issues, please post the icepyx code that you are using that's returning the error along with the error traceback and icepyx version.

**Comment by weiji14** [comment]
Haven't tested this, but it seems as though NSIDC has opened up cloud access to everyone? See https://nsidc.org/data/user-resources/data-announcements/data-set-updates-new-earthdata-cloud-access-option-icesat-2-and-icesat-data-sets. What ICESat-2 data product are you trying to access @Siyuanhou? ATL03, ATL06, or some other one?

**Comment by Siyuanhou** [comment]
Thank you for your reply, I want to use the product of ATL03 to calculate the bathymetry in shallow region.The function of icepyx from the latest link , but it doesn't works(the web of AWS S3 is invalid). I didn't find a solution.Maybe you can help me.






















--

syH
Xiamen unversity
***@***.***




At 2022-10-01 00:38:25, "Wei Ji" ***@***.***> wrote:

Haven't tested this, but it seems as though NSIDC has opened up cloud access to everyone? See https://nsidc.org/data/user-resources/data-announcements/data-set-updates-new-earthdata-cloud-access-option-icesat-2-and-icesat-data-sets. What ICESat-2 data product are you trying to access @Siyuanhou? ATL03, ATL06, or some other one?

**Comment by Siyuanhou** [comment]
Thanks for your reply.I just used this data. I need to download a lot of data.How to join the access list with NSIDC for beta test access to ICESat-2 data in the cloud？ How to filter and download batch data when not in the list？

I will check my code and reply to you soon. It can be downloaded normally half a year ago until the latest.The error is reported as follows. 










--

SY Hou
Xiamen University ，China
***@***.***




At 2022-09-27 23:03:41, "Jessica Scheick" ***@***.***> wrote:

Hello @Siyuanhou - thanks for reaching out. The capability_url you cited is for cloud data access (only). Are you on the early access list with NSIDC for beta test access to ICESat-2 data in the cloud? If not, you will not be able to create the proper credentials to access ICESat-2 data in the cloud (and you would likely not be downloading the data in a cloud-access scenario).

If you continue to have issues, please post the icepyx code that you are using that's returning the error along with the error traceback and icepyx version.

**Comment by weiji14** [comment]
The cloud data access is still quite new, but try following the instructions at https://nsidc.org/data/user-resources/help-center/nasa-earthdata-cloud-data-access-guide. I just tried it on https://hub.aws-uswest2-binder.pangeo.io/hub/login and it seems to work, though the setup is a bit complicated for now. Basic steps seems to be:

1. Get credentials from https://data.nsidc.earthdatacloud.nasa.gov/s3credentials, and input these lines into the terminal
```
export AWS_ACCESS_KEY_ID=<your_accessKeyId>
export AWS_SECRET_ACCESS_KEY=<your_secretAccessKey>
export AWS_SESSION_TOKEN=<you_sessionToken>
```

2. Install some AWS command line interface tool, e.g.

```bash
pip install awscli
```

3. Run some test command to list the files like:

```bash
aws s3 ls s3://nsidc-cumulus-prod-protected/ATLAS/ATL03/005/2018/10/14/
```
which should produce an output like:

```
2021-11-14 21:26:51  419002911 ATL03_20181014000347_02350101_005_01.h5
2021-11-14 21:26:59    3192825 ATL03_20181014000347_02350101_005_01.h5.dmrpp
2021-11-14 21:13:19 1850440524 ATL03_20181014001049_02350102_005_01.h5
2021-11-14 21:13:38   12453743 ATL03_20181014001049_02350102_005_01.h5.dmrpp
2021-11-15 07:56:20 1775356258 ATL03_20181014001920_02350103_005_01.h5
2021-11-15 07:56:40   12186366 ATL03_20181014001920_02350103_005_01.h5.dmrpp
2021-11-15 18:14:22 1039203722 ATL03_20181014002445_02350104_005_01.h5
2021-11-15 18:14:39    8055791 ATL03_20181014002445_02350104_005_01.h5.dmrpp
2021-11-16 08:06:43  308164510 ATL03_20181014002954_02350105_005_01.h5
...
```

If you can get this far, then great! That means you have access to ICESat-2 data in the cloud. As for how to use `icepyx` to read these cloud data, we'll probably need to update the notebook at https://icepyx.readthedocs.io/en/latest/example_notebooks/IS2_cloud_data_access.html to make it clearer how this can actually be used in a more user-friendly way.

**Comment by Siyuanhou** [comment]
Thank you for your patient reply. I'll try to adjust it.













--

SY Hou
Xiamen University ，China
***@***.***




At 2022-10-04 05:09:02, "Wei Ji" ***@***.***> wrote:

The cloud data access is still quite new, but try following the instructions at https://nsidc.org/data/user-resources/help-center/nasa-earthdata-cloud-data-access-guide. I just tried it on https://hub.aws-uswest2-binder.pangeo.io/hub/login and it seems to work, though the setup is a bit complicated for now. Basic steps seems to be:

Get credentials from https://data.nsidc.earthdatacloud.nasa.gov/s3credentials, and input these lines into the terminal
export AWS_ACCESS_KEY_ID=<your_accessKeyId>
export AWS_SECRET_ACCESS_KEY=<your_secretAccessKey>
export AWS_SESSION_TOKEN=<you_sessionToken>

Install some AWS command line interface tool, e.g.
pip install awscli
Run some test command to list the files like:
aws s3 ls s3://nsidc-cumulus-prod-protected/ATLAS/ATL03/005/2018/10/14/

which should produce an output like:

2021-11-14 21:26:51  419002911 ATL03_20181014000347_02350101_005_01.h5
2021-11-14 21:26:59    3192825 ATL03_20181014000347_02350101_005_01.h5.dmrpp
2021-11-14 21:13:19 1850440524 ATL03_20181014001049_02350102_005_01.h5
2021-11-14 21:13:38   12453743 ATL03_20181014001049_02350102_005_01.h5.dmrpp
2021-11-15 07:56:20 1775356258 ATL03_20181014001920_02350103_005_01.h5
2021-11-15 07:56:40   12186366 ATL03_20181014001920_02350103_005_01.h5.dmrpp
2021-11-15 18:14:22 1039203722 ATL03_20181014002445_02350104_005_01.h5
2021-11-15 18:14:39    8055791 ATL03_20181014002445_02350104_005_01.h5.dmrpp
2021-11-16 08:06:43  308164510 ATL03_20181014002954_02350105_005_01.h5
...


If you can get this far, then great! That means you have access to ICESat-2 data in the cloud. As for how to use icepyx to read these cloud data, we'll probably need to update the notebook at https://icepyx.readthedocs.io/en/latest/example_notebooks/IS2_cloud_data_access.html to make it clearer how this can actually be used in a more user-friendly way.

**Comment by JessicaS11** [comment]
> As for how to use icepyx to read these cloud data, we'll probably need to update the notebook at https://icepyx.readthedocs.io/en/latest/example_notebooks/IS2_cloud_data_access.html to make it clearer how this can actually be used in a more user-friendly way.

This is on my to-do list now that NSIDC has publicly released the data. I suspect @Siyuanhou may have identified the issue with:
> the web of AWS S3 is invalid

It's possible that with the public release they updated the s3 urls required to access the data on the cloud, and because they weren't public (i.e. included in metadata from CMR) before, icepyx was constructing them manually.
