### ISSUE TITLE
Server error on Query request.

### ISSUE THREAD

**Issue by mmazzolini** [icesat2py/icepyx#375]
Hi everyone, I'm trying to obtain some ATL03 data with icepyx. The code is the following:
```
S_daterange = ['2019-01-01','2021-05-01']
coords_S = [-2, 41.5, -0.01, 43.5]

region_S = ipx.Query('ATL03', 
                      coords_S,
                      S_daterange)
region_S.avail_granules(ids=True)
region_S.earthdata_login(#############)
region_S.download_granules(icdatapath+'ATL03_'+AOIname+'/')
```

several orders are normally processed, as I would expect. After some orders correctly processed (I also received the email when the order is complete) I receive the following error:

```
Data request  10  of  18  is submitting to NSIDC
Traceback (most recent call last):
  File "/net/hypatia/uio/fs01/lh-mn-geofag-felles/projects/snowdepth/marcomaz/Izas/mimi_download.py", line 86, in <module>
    region_S.download_granules(icdatapath+'ATL03_'+AOIname+'/')
  File "/uio/kant/geo-geohyd-u1/marcomaz/anaconda3/envs/xdem/lib/python3.10/site-packages/icepyx/core/query.py", line 899, in download_granules
    self.order_granules(verbose=verbose, subset=subset, **kwargs)
  File "/uio/kant/geo-geohyd-u1/marcomaz/anaconda3/envs/xdem/lib/python3.10/site-packages/icepyx/core/query.py", line 828, in order_granules
    self._granules.place_order(
  File "/uio/kant/geo-geohyd-u1/marcomaz/anaconda3/envs/xdem/lib/python3.10/site-packages/icepyx/core/granules.py", line 295, in place_order
    request.raise_for_status()
  File "/uio/kant/geo-geohyd-u1/marcomaz/anaconda3/envs/xdem/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 501 Server Error: 501 for url: https://n5eil02u.ecs.nsidc.org/egi/request?short_name=ATL03&version=005&temporal=2021-05-01T00%3A00%3A00Z%2C2022-09-01T23%3A59%3A59Z&bounding_box=-2.0%2C41.5%2C-0.01%2C43.5&page_size=10&page_num=10&request_mode=async&email=mazzolini.marc%40gmail.com&include_meta=Y&client_string=icepyx&time=2021-05-01T00%3A00%3A00%2C2022-09-01T23%3A59%3A59&bbox=-2.0%2C41.5%2C-0.01%2C43.5
```
If I follow the URL and I get to this page:
```
<eesi:Exception>
<Code>InternalError</Code>
<Message>No granules returned by CMR</Message>
</eesi:Exception>
```

Any idea how to fix this one? I'm not sure it's an icepyx problem.. thanks a lot for the help anyway.

**Comment by JessicaS11** [comment]
Hello @mmazzolini! Thanks for posting your issue. You are right that the error itself is not coming from icepyx, but rather the data center. Based on the message, it looks like icepyx is submitting a valid request and there are not results being found. Could you share the output for `icepyx.__version__`? I'm noting that a few of the defaults in the url submitted appear to be older values. We may need to reach out to NSIDC directly for user support from their end.

**Comment by mmazzolini** [comment]
Thanks for the quick answer. My icepyx version should be `0.3.4`..

**Comment by arrueegg** [comment]
I have the same issue but i'm using icepyx 0.6.3 already, is there already a solution?

**Comment by JessicaS11** [comment]
Closing as stale. If any users are still having this problem, please feel free to post a new issue (ideally referencing this one) with updated code for a minimally working example.
