### ISSUE TITLE
CMR returning duplicate results

### ISSUE THREAD

**Issue by JessicaS11** [icesat2py/icepyx#378]
```
reg_a = ipx.Query('ATL06',[-55, 68, -48, 71],['2019-02-20','2019-02-28'])
reg_a.avail_granules()
```
Now returns a list of 8 granules instead of 4. However, it's just the same list twice. It's evident if you go directly to the [cmr url](https://cmr.earthdata.nasa.gov/search/granules?short_name=ATL06&version=005&temporal=2019-02-20T00:00:00Z,2019-02-28T23:59:59Z&bounding_box=-55.0,68.0,-48.0,71.0&page_size=2000) as well, which has led me to conclude there's been a change in CMR metadata returned that the previous method of results parsing doesn't account for.

This issue aims to:
1) let folks know about the problem (@jpswinski @weiji14 @tsutterley), as it affects existing versions of icepyx that other tools use
2) provide a public forum for learning more about what changed and discussing the best approach moving forward (@betolink @asteiker @andypbarrett)

**Comment by JessicaS11** [comment]
From @asteiker:
> Yes, now that the data are publicly available in the cloud, if you search just on the short name, then you will see two copies of every granule, reflecting both the on-prem (nsidc_ecs) and cloud (nsidc_cprd) storage locations.

**Comment by tsutterley** [comment]
You can add the provider flag to switch between the two `&provider=NSIDC_ECS` or `&provider=NSIDC_CPRD`

**Comment by JessicaS11** [comment]
> You can add the provider flag to switch between the two `&provider=NSIDC_ECS` or `&provider=NSIDC_CPRD`
Can we assume there's a 1-1 relationship between the two granule lists? Or would it be better to assume CPRD is a subset (that could also be the equivalent set) of ECS (in which case we might want to fix to ECS for discovery initially, then let the user know if not everything is available via CPRD)?

**Comment by tsutterley** [comment]
There might be a lag upon a data release getting the data to s3, but they should be parallel

**Comment by JessicaS11** [comment]
To my surprise, converting the response from [url](https://cmr.earthdata.nasa.gov/search/granules?short_name=ATL06&version=005&temporal=2019-02-20T00:00:00Z,2019-02-28T23:59:59Z&bounding_box=-55.0,68.0,-48.0,71.0&page_size=2000&provider=NSIDC_ECS) (i.e. after adding `&provider=NSIDC_ECS`) to a json results in an empty "entry" list, even though it returns the expected results in a browser...

**Comment by tsutterley** [comment]
the [JSON return from CMR](https://cmr.earthdata.nasa.gov/search/granules.json?short_name=ATL06&version=005&temporal=2019-02-20T00:00:00Z,2019-02-28T23:59:59Z&bounding_box=-55.0,68.0,-48.0,71.0&page_size=2000&provider=NSIDC_ECS) looks fine?

**Comment by JessicaS11** [comment]
> the [JSON return from CMR](https://cmr.earthdata.nasa.gov/search/granules.json?short_name=ATL06&version=005&temporal=2019-02-20T00:00:00Z,2019-02-28T23:59:59Z&bounding_box=-55.0,68.0,-48.0,71.0&page_size=2000&provider=NSIDC_ECS) looks fine?

Apparently VSCode can't handle multiple debugging sessions at once. So even though (as you point out) the CMR looked fine in a browser, it was not fine programmatically in that debug session. 🙄 Thanks for quickly confirming it SHOULD work.

**Comment by betolink** [comment]
Not entirely related to this but, are you guys presenting demoing icepyx at the IS2 meeting?
