### ISSUE TITLE
Additional steps needed for Jupyter notebook PYTHONPATH

### ISSUE THREAD

**Issue by asteiker** [icesat2py/icepyx#39]
Following the install guidance: "Provided the location of the repo is part of your $PYTHONPATH, you should simply be able to add import icepyx to your Python document" I ran into complications when trying to run ICESat-2_DAAC_DataAccess_Example.ipynb from my fork. I set the repo location via command line (Mac OSX):
`open .bash_profile` 
`export PYTHONPATH="${PYTHONPATH}:/path/to/repo"` 

And I successfully imported `icepyx` in python in a terminal window.

However once I loaded up Jupyter Lab and tried running the notebook, the install failed. Following [this guidance](https://stackoverflow.com/questions/34976803/sys-path-different-in-jupyter-and-python-how-to-import-own-modules-in-jupyter) I ended up creating an ipython config file:

```$ipython profile create
$ ipython locate
`/Users/username/.ipython`
$ cd /Users/username/.ipython
$ vi profile_default/ipython_config.py
c.InteractiveShellApp.exec_lines = [
    'import sys; sys.path.append("/path/to/your/module")'
]
```

And this did the trick. I'm not sure if others have run into this problem or if this is the best approach but it may be worth updating the install instructions if this is a more common issue.

**Comment by tsutterley** [comment]
My guess is that jupyter lab doesn't source from `.bash_profile` but rather from `.bashrc`.  Could probably add your `$PYTHONPATH` to `.bashrc` or to source `.bash_profile` in `.bashrc`?

see https://github.com/jupyterlab/jupyterlab/issues/1733

**Comment by asteiker** [comment]
I'm not sure if a .bashrc exists for me. I get a "does not exist" error when trying to open it like I did with `.bash_profile` and I don't see it listed when I list my hidden files. 

I'm not well-versed in setting python paths and environments (obviously!) so hopefully this is not an issue for other users of icepyx, or maybe my paths are set up uniquely somehow. Again I did get it to work at least so at least I'm all set for now.

**Comment by JessicaS11** [comment]
I'm glad you got it working - I think Tyler's got a great point, and we can definitely add this pointer to the install instructions, since we provide notebooks and people are likely to be using JupyterLab. Does either of you want to submit a pull request?

**Comment by JessicaS11** [comment]
Closing this issue now that icepyx is available for installation with conda: `conda install -c conda-forge icepyx`
