### ISSUE TITLE
cannot import  'icesat2data' from 'icepyx'

### ISSUE THREAD

**Issue by Zilhe** [icesat2py/icepyx#394]
Hi, 

I have encountered an issue with the command 'from icepyx import icesat2data as ipd'

I've tried to install the icepyx with both the conda and pip. But the issue occurred in both cases. 

The screenshot of this issue is  pasted.

![screen1](https://user-images.githubusercontent.com/69462500/210298312-0fbf454a-11d5-4478-a74e-bf5a11dfcca1.png)

**Comment by JessicaS11** [comment]
Hello @Zilhe! Thanks for getting in touch. Can you please share where you found the example code you are using? The `ipd.Icesat2Data` syntax has been deprecated for going on years now. We've tried to leave appropriate notes on the pages we have control over. Whenever possible, we encourage uses to refer to our [documentation pages ](https://icepyx.readthedocs.io/en/latest/)and the examples there (see the left sidebar) for the most up-to-date syntax. In your screen-shot use case, that would be:
```
import icepyx as ipx
region = ipx.Query(short_name, spatial_extent, date_range)
```

Please let us know if you continue to run into issues getting started with icepyx!

**Comment by Zilhe** [comment]
> Hello @Zilhe! Thanks for getting in touch. Can you please share where you found the example code you are using? The `ipd.Icesat2Data` syntax has been deprecated for going on years now. We've tried to leave appropriate notes on the pages we have control over. Whenever possible, we encourage uses to refer to our [documentation pages ](https://icepyx.readthedocs.io/en/latest/)and the examples there (see the left sidebar) for the most up-to-date syntax. In your screen-shot use case, that would be:
> 
> ```
> import icepyx as ipx
> region = ipx.Query(short_name, spatial_extent, date_range)
> ```
> 
> Please let us know if you continue to run into issues getting started with icepyx!

Thank you very much! It works with the recommended code.

I found the example code on https://github.com/ICESAT-2HackWeek/surface_classification. I just realized the code was uploaded two years ago, so the syntax may be outdated. I will study the documentation pages carefully. Thank you!

**Comment by JessicaS11** [comment]
Ah - thank you! We have some notes in the data access portions of those materials, but did not update each of the tutorials that use icepyx. Please consider applying for this summer's [ICESat-2 Hackweek](https://icesat-2.hackweek.io/) (applications coming soon) to learn more about working with ICESat-2 data in the cloud!
