### ISSUE TITLE
EarthData authentication

### ISSUE THREAD

**Issue by nmt28** [icesat2py/icepyx#423]
Hi, this may have been solved already but it looks like EarthData now needs a token which icepyx is not set up to take:

['This service has been retired. The new authentication service is described at https://wiki.earthdata.nasa.gov/display/EL/How+to+Generate+a+User+Token.']

**Comment by JessicaS11** [comment]
Hello @nmt28 - can you share what version of icepyx you're using? Our most recent release (0.7.0) included some authentication updates (namely using [earthaccess](https://nsidc.github.io/earthaccess/) behind the scenes now) given the impending retirement of a certain token type at NSIDC. The hope was that this would mean users didn't need to know/worry about the change, but it *does* require the most recent version of icepyx. If it's an issue that's still happening with the newest version, then we will need to dig in.
