### ISSUE TITLE
debug tests behind EDL - failing builds for PRs to main

### ISSUE THREAD

**Issue by rwegener2** [icesat2py/icepyx#448]
PR #447 is an example of a build that ran well with merges to `development` or `release`, but the build fails due to an authentication error when merging to `main`. This was an issue for the release of both `0.7.0` and `0.8.0`, after the integration of `earthaccess`.

The main branch is failing because:
> because the behind_NSIDC_login test suite is only run on the main branch (so in the list of checks, the "branch" test run passes, but when the additional tests are triggered for the "pull request" (what the merged code will look like) it fails).
(From @JessicaS11 in #447)

**Comment by JessicaS11** [comment]
Per the `.travis.yml` setup, including the string `nsidc_tests` in the commit message should trigger the `test_behind_earthdata_login` tests.
