### ISSUE TITLE
Allow installing with pip

### ISSUE THREAD

**Issue by scottyhq** [icesat2py/icepyx#45]
Installing icepyx as a Python package will facilitate things for users. Currently this command to install from the master branch works, but dependencies are note listed so importing in a new environment would fail.
`pip install git+https://github.com/icesat2py/icepyx.git`

```
>>> import icepyx
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/scott/miniconda3/envs/icepyx/lib/python3.7/site-packages/icepyx/__init__.py", line 1, in <module>
    from .core import is2class
  File "/Users/scott/miniconda3/envs/icepyx/lib/python3.7/site-packages/icepyx/core/is2class.py", line 1, in <module>
    import numpy as np
ModuleNotFoundError: No module named 'numpy'
```
@JessicaS11 - I could follow up with a PR to fix this if you'd like

**Comment by JessicaS11** [comment]
@scottyhq That would be excellent and greatly appreciated! I know it's fairly early in development still, but would you recommend making icepyx available on PyPI and/or Conda before the Hackweek as well?

**Comment by dshean** [comment]
Sounds good.  Can we add the `-e` flag, so participants can modify source and test during the hackweek?  There are also advantages to having them pip install their own fork, so they can push any fixes/contributions upstream...

**Comment by scottyhq** [comment]
> I know it's fairly early in development still, but would you recommend making icepyx available on PyPI and/or Conda before the Hackweek as well? 

Up to you @JessicaS11! Having packages facilitates more widespread use, but its understandable if you want to wait a bit while you're in early development. Once the PR above is merged you can also use github tags in lieu of package releases. For example, if you want a bookmark for the state of things during the hackweek you can run `git tag v0.0.1; git push --tags`. That way you can install a specific tagged version with `pip install  git+https://github.com/icesat2py/icepyx.git@v0.0.1`
