### ISSUE TITLE
ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it

### ISSUE THREAD

**Issue by FlorinZai** [icesat2py/icepyx#465]
Hello, 

I am dealing with a connection when trying to order the granules
region.order_vars.avail(options=True)

I am logged in and managed a few days ago to download data with the same code and it worked without any problems.

---------------------------------------------------------------------------
ConnectionRefusedError                    Traceback (most recent call last)
File [c:\Users\zaifl\miniconda3\envs\icesat\lib\site-packages\urllib3\connection.py:174](file:///C:/Users/zaifl/miniconda3/envs/icesat/lib/site-packages/urllib3/connection.py:174), in HTTPConnection._new_conn(self)
    173 try:
--> 174     conn = connection.create_connection(
    175         (self._dns_host, self.port), self.timeout, **extra_kw
    176     )
    178 except SocketTimeout:

File [c:\Users\zaifl\miniconda3\envs\icesat\lib\site-packages\urllib3\util\connection.py:95](file:///C:/Users/zaifl/miniconda3/envs/icesat/lib/site-packages/urllib3/util/connection.py:95), in create_connection(address, timeout, source_address, socket_options)
     94 if err is not None:
---> 95     raise err
     97 raise socket.error("getaddrinfo returns an empty list")

File [c:\Users\zaifl\miniconda3\envs\icesat\lib\site-packages\urllib3\util\connection.py:85](file:///C:/Users/zaifl/miniconda3/envs/icesat/lib/site-packages/urllib3/util/connection.py:85), in create_connection(address, timeout, source_address, socket_options)
     84     sock.bind(source_address)
---> 85 sock.connect(sa)
     86 return sock

ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it

During handling of the above exception, another exception occurred:

NewConnectionError                        Traceback (most recent call last)
File [c:\Users\zaifl\miniconda3\envs\icesat\lib\site-packages\urllib3\connectionpool.py:703](file:///C:/Users/zaifl/miniconda3/envs/icesat/lib/site-packages/urllib3/connectionpool.py:703), in HTTPConnectionPool.urlopen(self, method, url, body, headers, retries, redirect, assert_same_host, timeout, pool_timeout, release_conn, chunked, body_pos, **response_kw)
...
--> 519     raise ConnectionError(e, request=request)
    521 except ClosedPoolError as e:
    522     raise ConnectionError(e, request=request)

ConnectionError: HTTPSConnectionPool(host='n5eil02u.ecs.nsidc.org', port=443): Max retries exceeded with url: /egi/capabilities/ATL03.006.xml (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000002049B7DF760>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')

**Comment by JessicaS11** [comment]
Hello @FlorinZai! Thanks for reaching out. NSIDC sometimes has their systems down for maintenance (it often happens on Wednesdays), which appears to be the case currently and likely explains your connection error. They're really good about putting a banner notice on the [ICESat-2 page](https://nsidc.org/data/icesat-2), so I usually check there first when I get a connection error. Unfortunately, there's not a whole lot any of us can do until they have things back up and running. If for some reason you still encounter any issues once the maintenance banner is gone, please do let us know and we can troubleshoot!

**Comment by FlorinZai** [comment]
Thanks @JessicaS11 for your quick response! I guess we'll have to wait a bit. I'll check their page from now on. 
Wish you the best,
