### ISSUE TITLE
figure out where the codecov reports went

### ISSUE THREAD

**Issue by JessicaS11** [icesat2py/icepyx#485]
Just noticed today that the codecov reports aren't being added to PRs, and the last PR that has one in codecov is from 9 months ago! Will need to dig in and update the integration to get the reports added back.

**Comment by weiji14** [comment]
Codecov announced in Sep 2021 that their old bash uploader is being deprecated, could that be related? https://about.codecov.io/blog/codecov-uploader-deprecation-plan

**Comment by JessicaS11** [comment]
Thanks for pointing me towards that, @weiji14!
