### ISSUE TITLE
make links work on both RTD and GitHub

### ISSUE THREAD

**Issue by JessicaS11** [icesat2py/icepyx#50]
Automatic links can only work within RTD OR GitHub, but not both simultaneously. Hard links won't update automatically as new commits are added to the repo. A potential solution is suggested in [this issue](https://github.com/readthedocs/readthedocs.org/issues/2926) post.

**Comment by weiji14** [comment]
Is this issue still valid? I visited the page on GitHub at https://github.com/icesat2py/icepyx/blob/development/examples/examples.rst and on ReadTheDocs at https://icepyx.readthedocs.io/en/development/getting_started/example_link.html. Clicking on both links takes me to correct Jupyter Notebook example at https://github.com/icesat2py/icepyx/blob/main/examples/ICESat-2_DAAC_DataAccess_Example.ipynb

**Comment by JessicaS11** [comment]
> Is this issue still valid? 

It's unclear. For the case you cite, there's no longer an issue (as you say).

What I may have meant (but did not articulate well) is that links using the `:ref:` rst directive do not render within GitHub. For instance, if you look at [`doc/source/index.rst`](https://github.com/icesat2py/icepyx/blob/development/doc/source/index.rst#id1) you'll see that the Quick Links at the top of the page don't render into valid, clickable links to those resources on GitHub, even though they take you to the right portions of the docs on RTD. As best I can tell, there's no way around this (Python itself has these unrendered :ref: directives in their docs if viewed on GitHub). Feel free to reopen if I'm mistaken, but I'm closing this issue since icepyx considers the RTD docs as the primary location for documentation produced from files that happen to live on (and be partially rendered by) GitHub.
