### ISSUE TITLE
Consolidate CI from Travis -> GitHub Actions

### ISSUE THREAD

**Issue by mfisher87** [icesat2py/icepyx#547]
I'm not very familiar with Travis, but I'm pretty used to Actions and have tools (e.g. https://github.com/nektos/act) and knowledge I can't apply to Travis. I think it'd be better for contributors to only have to know one or the other. Thoughts?

**Comment by JessicaS11** [comment]
I'm game to transition from Travis to GitHub actions. @mfisher87, I think you partially did this in setting up the v2 branch? Are you game to implement this change, with the manual trigger option we talked about for enabling tests needing auth to run (with approval) for PRs from forks?

I will add the task of setting up the necessary secrets for early next week.

**Comment by mfisher87** [comment]
I'm on it :) But I think I need a refresher on the manual trigger thing. Where'd we talk about that? :thinking: :eyes: 

The v2 branch currently includes running the tests that don't require authentication in GitHub Actions, so I can open a PR with that workflow, and also add an "integration test" workflow that does require the creds.
