### ISSUE TITLE
Travis failing on all PRs due to EDL auth error

### ISSUE THREAD

**Issue by mfisher87** [icesat2py/icepyx#558]
```
FAILED icepyx/tests/test_auth.py::test_get_session - icepyx.core.auth.AuthenticationError: Earthdata authentication failed. Check output for error message

FAILED icepyx/tests/test_auth.py::test_get_s3login_credentials - icepyx.core.auth.AuthenticationError: Earthdata authentication failed. Check output for error message

FAILED icepyx/tests/test_auth.py::test_login_function - icepyx.core.auth.AuthenticationError: Earthdata authentication failed. Check output for error message
```

https://app.travis-ci.com/github/icesat2py/icepyx/builds/271856777

**Comment by mfisher87** [comment]
@JessicaS11 @weiji14 just realized this is blocking merge of all PRs. :scream:

I'm trying to figure out what's going on and I don't see any change in the code that corresponds with the start of the failures. Is it possible that a credential was changed and Travis secrets weren't updated?

**Comment by JessicaS11** [comment]
The place I've noticed the auth tests failing on Travis CI tests is the PRs submitted from forks. This is expected behavior, as noted in #272.

**Comment by mfisher87** [comment]
You're so right. I was sure I'd also seen it on one of my PRs which was not from a fork, but now that I'm looking again, I was clearly wrong! I'm going to pin #272 to keep it more visible!
