### ISSUE TITLE
installation issue

### ISSUE THREAD

**Issue by bradlipovsky** [icesat2py/icepyx#83]
When attempting to install icepyx locally, I experience the following error,
```
! cd ..; [ -d icepyx ] || git clone https://www.github.com/icesat2py/icepyx.git
sys.path.append(os.path.join(os.getcwd(), '..'))
from icepyx import icesat2data as ipd
```

The download goes fine,

> Cloning into 'icepyx'...
> warning: redirecting to https://github.com/icesat2py/icepyx.git/
> remote: Enumerating objects: 15, done.
> remote: Counting objects: 100% (15/15), done.
> remote: Compressing objects: 100% (13/13), done.
> remote: Total 2214 (delta 3), reused 12 (delta 2), pack-reused 2199
> Receiving objects: 100% (2214/2214), 11.02 MiB | 14.83 MiB/s, done.
> Resolving deltas: 100% (1253/1253), done.

But then when I go to `import`,

> ---------------------------------------------------------------------------
> ImportError                               Traceback (most recent call last)
> <ipython-input-15-a4a6c7bdf710> in <module>
>       1 get_ipython().system(' cd ..; [ -d icepyx ] || git clone https://www.github.com/icesat2py/icepyx.git')
>       2 sys.path.append(os.path.join(os.getcwd(), '..'))
> ----> 3 from icepyx import icesat2data as ipd
> 
> ImportError: cannot import name 'icesat2data'

**Comment by dshean** [comment]
I generally try to avoid modifying sys.path, and instead use pip to manage installs when not possible with conda.

If you cd into the icepyx directory containing `setup.py`, you should be able to `pip install -e .` to install in developer mode (so you can modify source code and see changes).  This will use the first `pip` found in your shell $PATH (run `which pip` to verify), which should hopefully be your primary Python install (e.g., conda environment rather than system Python).

**Comment by dshean** [comment]
@JessicaS11, are others planning to modify the installation instructions in README, or should I submit a PR?

**Comment by bradlipovsky** [comment]
Thanks @dshean that worked.  I'll leave the issue open because your question seems like a good one.

**Comment by loudTom** [comment]
Hi, the installation instructions will be updated shortly to clarify the existing installation process, and outline how it can be installed from PyPI.

**Comment by JessicaS11** [comment]
The updated instructions are now in the development (default) branch on the readme page (and will soon be available on read the docs as well). @bradlipovsky and @dshean, please let us know if you think they need additional updates (feel free to make those changes as well). @bradlipovsky, I've also found that if you're working in JupyterHub on Pangeo, you need to restart the kernel after the local install.
