### ISSUE TITLE
Tidier git history using squash merge

### ISSUE THREAD

**Issue by weiji14** [icesat2py/icepyx#93]
Awesome to see so many new contributors joining `icepyx`! I'm sure we'll all get some great science done, but if I could make one small request - which is to keep the git history nice looking going forward. This is what the graph looks like at the moment:

![Icepyx git history graph](https://user-images.githubusercontent.com/23487320/85906599-e6666f00-b862-11ea-98c3-02f8abc28007.png)

It's fine to do merge commits when it's just one or two people working on a repository, but bigger projects with tens if not hundreds of contributors use [squash merge commits](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/about-pull-request-merges#squash-and-merge-your-pull-request-commits). This keeps the git history linear looking, and we don't have big diffs from every single commit (especially important since jupyter notebooks can run into several MBs).

**Comment by JessicaS11** [comment]
Thanks @weiji14 for this suggestion. I've updated the settings to require a linear git history via squash merge commits to the development branch to which PRs are submitted.
